language: java
dist: trusty
sudo: false
install: true

addons:
  sonarcloud:
    organization: "creatingsolutions-github" # the key of the org you chose at step #3
    token:
      secure: "jptgGKZKGN1aK932NX2bQckEXBQsmtMWZhQ5tyJYKJxes6b3x1svG3Fy3PSieYOxT5tRtFoFRvojQXCljMpnkhyGLKfFjCsTefe3HtPKw9lqLIiuY6hLLFl5QFmb/W8FE/l6G8LeVjqVN2TTijbWCuo7aTazhClvn7icNw+rdpTBdds/qcORxj+IVZe4LFN6P2xOAvU1gSR+bTaHg9CH33iqWdM3FrWqZJmz988lfCrtcZ+AYbCbn1q7q295lD+z2AUSh6B6cn8KcO+ShWr0bYl005HzUXE+Huj4bcI7/Dcx1Gmu2YRUx33yp65TDsKoN8TdukIZEUWR44Fk1p0nECh2n3CUGj7xB7PVLstGZxTwTgQ7KZapNavIuY/JHfoggOy5SZfrkDHCRdR7WGTeuixOaZpNXQPfDF7BfidL43TssLVtu6ptMI5ohpdCv5B/hg0ztK05xSbNgk/jciFvjyHUDhUk3mMCCmd/1wHEW1v+4XjrSQ2cbRn735XAbv0yrZ7gv+OCWM+LUPiHA+XDKrEyd9pvODhtMn93KFh3rTmdGrML5BM40Fklok7yUJhy3nUdBoOhY9aAf9yXyEP5GXl1s14yKnzw1YqytJQqBrru7U7Pnj8wuVwfHIbMgajA8DWLo+38h0DuEKasAkUf9u3ASgTH4Bflpc4ji/CMK6c="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
